services:
  blog-postgres:
    container_name: ${POSTGRES_INITDB_CONTAINER}
    image: postgres:latest
    ##build:
    ##  context: ./
    ##  dockerfile: Dockerfile
    restart: always
    command: -p ${POSTGRES_INITDB_PORT}
    ports:
      - 127.0.0.1:${POSTGRES_INITDB_PORT}:${POSTGRES_INITDB_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_INITDB_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m
    networks:
      - html
networks:
  html:
    external: true
    name: html